First pass

diff --git a/shifu b/shifu
--- a/shifu
+++ b/shifu
@@ -95,6 +95,17 @@ _shifu_setup() {
   _shifu_validate_help_flags
   _shifu_help_case_pattern
   _shifu_help_display_flags
+  _shifu_help_short_chars
+}
+
+_shifu_help_short_chars() {
+  shifu_help_short=""
+  _shifu_set_for_looping shifu_help_flags_list shifu_help_flags
+  for shifu_help_flag in $shifu_help_flags_list; do
+    case "$shifu_help_flag" in
+      -?) _shifu_append_short shifu_help_short "${shifu_help_flag#-}" ;;
+    esac
+  done
 }
 
 # api
@@ -187,6 +198,24 @@ _shifu_append_list() {
   eval "$1=\"\${$1:-}\$2\$shifu_list_delim\""
 }
 
+_shifu_append_short() {
+  eval "$1=\"\${$1:+\$$1|}\$2\""
+}
+
+_shifu_collect_short_flags() {
+  shifu_csf_kind="$1"; shift
+  while [ $# -gt 0 ] && [ "$1" != -- ]; do
+    case "$1" in
+      -?) if [ "$shifu_arg_scope" = defer ]; then
+            _shifu_append_short "shifu_defer_short_$shifu_csf_kind" "${1#-}"
+          else
+            _shifu_append_short "shifu_short_$shifu_csf_kind" "${1#-}"
+          fi ;;
+    esac
+    shift
+  done
+}
+
 shifu_itr_list() {
   if ! [ "${shifu_itr_temp+set}" ]; then
     eval "shifu_itr_temp=\$$1_LIST"
@@ -243,6 +272,7 @@ _shifu_run() {
   _shifu_load_cur_cmd "$1"
   shifu_cmd="$1"; shift
   shifu_required_variables=""
+  shifu_defer_short_bin=""
   while [ $# -ne 0 -a -n "${shifu_cmd_subs:-}" ]; do
     _shifu_parse_args true "$shifu_cur_cmd" "$@"
     shifu_mode=$shifu_mode_cmds_run
@@ -279,11 +309,15 @@ _shifu_parse_args() {
   _shifu_in_remaining=false
   _shifu_end_of_options=false
   shifu_arg_stmt=""
+  shifu_short_bin=""
   shifu_parse_eager="$1"; shifu_cmd="$2"; shift 2
   [ "$shifu_parse_eager" = true ] && shifu_required_variables_eager=""
   shifu_required_positionals=""
   _shifu_case_open
   _shifu_case_inline_deferred
+  if [ "$shifu_parse_eager" = false ]; then
+    [ -n "${shifu_defer_short_bin:-}" ] && shifu_short_bin="${shifu_short_bin:+$shifu_short_bin|}$shifu_defer_short_bin"
+  fi
   _shifu_case_arm_help
   "$shifu_cmd"
   _shifu_case_close
@@ -529,6 +563,7 @@ _shifu_cmd_optb() {
       ;;
     $shifu_mode_args_run)
       _shifu_case_arm_begin "$shifu_arg_scope" "$@"
+      _shifu_collect_short_flags bin "$@"
       shift $shifu_opt_count
       _shifu_guard_arg_order "$1"
       _shifu_var_default "$1" "$2"
@@ -945,9 +980,32 @@ _shifu_case_arm_help() {
   _shifu_append_on_new_line shifu_case_stmt "  $shifu_help_pattern) _shifu_help \"$shifu_cmd\" 0 ;; "
 }
 
+_shifu_case_arm_bundle() {
+  shifu_bundle_bin="$shifu_short_bin"
+  [ -n "${shifu_help_short:-}" ] && shifu_bundle_bin="${shifu_bundle_bin:+$shifu_bundle_bin|}$shifu_help_short"
+  [ -n "$shifu_bundle_bin" ] || return 0
+  if [ $shifu_mode -eq $shifu_mode_args_comp ]; then
+    shifu_bundle_ack=""
+    shifu_bundle_default="_shifu_comp_done=true"
+  else
+    shifu_bundle_ack="; _shifu_args_parsed=\$((_shifu_args_parsed - 1))"
+    shifu_bundle_default="echo \"Invalid option: \$1\"; _shifu_help \"\$shifu_cmd\" 1"
+  fi
+  shifu_case_stmt="$shifu_case_stmt
+  -[!-]?*)
+    _shifu_body=\"\${1#-}\"; _shifu_tail=\"\${_shifu_body#?}\"; _shifu_head=\"\${_shifu_body%\"\$_shifu_tail\"}\"
+    case \"\$_shifu_head\" in"
+  [ -n "$shifu_bundle_bin" ] && shifu_case_stmt="$shifu_case_stmt
+    $shifu_bundle_bin) shift; set -- \"-\$_shifu_head\" \"-\$_shifu_tail\" \"\$@\"$shifu_bundle_ack ;;"
+  shifu_case_stmt="$shifu_case_stmt
+    *) $shifu_bundle_default ;;
+  esac ;;"
+}
+
 _shifu_case_arm_invalid() {
   [ "${shifu_parse_eager:-true}" = false ] && shifu_case_stmt="$shifu_case_stmt
   --) _shifu_end_of_options=true; shift; _shifu_ack_arg ;;"
+  _shifu_case_arm_bundle
   shifu_case_stmt="$shifu_case_stmt
   -*) echo \"Invalid option: \$1\"; _shifu_help \"\$shifu_cmd\" 1 ;;
   *)"
