Put api functions at top, get help strings correctly

diff --git a/shifu b/shifu
--- a/shifu
+++ b/shifu
@@ -13,6 +13,99 @@ shifu_reset="$(tput sgr0)"
 
 shifu_log_flag='--shifu-log'
 
+shifu_cmd_name() {
+  # 1: command name
+  [ $# -ne 1 ] && { echo "Commands cannot contain spaces got: \"$@\""; exit 1; }
+  [ $mode -ne $shifu_mode_args ] && cmd_name="$1"
+}
+
+shifu_cmd_help() {
+  # @: help string
+  [ $mode -ne $shifu_mode_args ] && cmd_help="$@"
+}
+
+shifu_cmd_long() {
+  # @: long help string
+  [ $mode -ne $shifu_mode_args ] && cmd_long="$@"
+}
+
+shifu_cmd_subs() {
+  # @: subcommand function names
+  [ $mode -ne $shifu_mode_args ] && cmd_subs="$@"
+}
+
+shifu_cmd_func() {
+  # @: command function name
+  [ $mode -ne $shifu_mode_args ] && cmd_func="$@"
+}
+
+shifu_arg() {
+  case $mode in
+    $shifu_mode_help) _shifu_arg_help "$@" ;;
+    $shifu_mode_args) _shifu_parse_arg "$@" ;;
+    *) return
+  esac
+}
+
+shifu_run() {
+  shifu_var_store mode parent arg arg_matched cmd cmd_name cmd_help cmd_long cmd_subs cmd_func
+  mode=$shifu_mode_cmds
+  parent="$1"; shift; "$parent"; shifu_cmds="$cmd_subs"
+  while [ $# -ne 0 ]; do
+    arg="$1"; shift
+    arg_matched=''
+    for cmd in $shifu_cmds; do
+      _shifu_clear_cmd_vars
+      "$cmd"
+      [ "$arg" != "$cmd_name" ] && continue
+      arg_matched=true
+      [ -n "$cmd_func" ] && break
+      parent="$cmd"
+      shifu_cmds="$cmd_subs"
+      break
+    done
+    [ "$arg_matched" = true -a -n "$cmd_func" ] && break
+    [ "$arg_matched" = true -a -n "$cmd_subs" ] && continue
+    echo "unknown command: $arg"
+    shifu_help "$parent"
+    exit 1
+  done
+  [ "$1" = "-h" -o "$1" = "--help" ] && shifu_help "$cmd" || "$cmd_func" "$@"
+  shifu_var_restore mode parent arg arg_matched cmd cmd_name cmd_help cmd_long cmd_subs cmd_func
+}
+
+shifu_parse_args() {
+  # 1: function, 2-: args to parse
+  shifu_var_store mode parse_stage case_stmt has_options
+  mode=$shifu_mode_args
+  parse_stage=0
+  case_stmt="case \$1 in -h|--help) shifu_help \$1; break ;; "
+  "$1"; shift # run the cmd function
+  [ $parse_stage -eq 0 ] && case_stmt="$case_stmt *) "
+  case_stmt="$case_stmt break ;; esac"
+  while true; do
+    eval "$case_stmt"
+  done
+  shifu_remaining_args=$(_shifu_save_remaining_args "$@")
+  shifu_var_restore mode parse_stage case_stmt has_options
+}
+
+shifu_help() {
+  shifu_var_store mode help_stage help_usage help_arguments help_options help_string has_options
+  mode=$shifu_mode_help
+  _shifu_clear_cmd_vars
+  help_stage=0 help_usage='' help_arguments='' help_options='' help_string=''
+  "$1"
+  [ -n "$help_usage" ] && help_usage="$cmd_name [OPTIONS] $help_usage"
+  [ -n "$cmd_help" ] && _shifu_add_to_help_string "$cmd_help"
+  [ -n "$cmd_long" ] && _shifu_add_to_help_string "$cmd_long"
+  [ -n "$help_usage" ] && _shifu_add_to_help_string "Usage\n\t$help_usage"
+  [ -n "$help_arguments" ] && _shifu_add_to_help_string "Arguments\n$help_arguments"
+  [ -n "$help_options" ] && _shifu_add_to_help_string "Options\n$help_options"
+  [ -n "$help_string" ] && echo "$help_string"
+  shifu_var_restore mode help_stage help_usage help_arguments help_options help_string has_options
+}
+
 # Write input arguments to stdout starting with green "shifu"
 shifu_log() {
   [ "$shifu_logging" = true ] && echo "${shifu_green}shifu${shifu_reset}  $@"
@@ -42,59 +135,6 @@ shifu_var_restore() {
     eval "$1=\$shifu_${1}_shifu; unset -v shifu_${1}_shifu"
     shift
   done
-}
-
-shifu_cmd_name() {
-  # 1: command name
-  [ $# -ne 1 ] && { echo "Commands cannot contain spaces got: \"$@\""; exit 1; }
-  [ $mode -eq $shifu_mode_cmds ] && cmd_name="$1"
-}
-
-shifu_cmd_help() {
-  # @: help string
-  [ $mode -eq $shifu_mode_cmds ] && cmd_help="$@"
-}
-
-shifu_cmd_long() {
-  # @: long help string
-  [ $mode -eq $shifu_mode_cmds ] && cmd_long="$@"
-}
-
-shifu_cmd_subs() {
-  # @: subcommand function names
-  [ $mode -eq $shifu_mode_cmds ] && cmd_subs="$@"
-}
-
-shifu_cmd_func() {
-  # @: command function name
-  [ $mode -eq $shifu_mode_cmds ] && cmd_func="$@"
-}
-
-shifu_run() {
-  shifu_var_store mode parent arg arg_matched cmd cmd_name cmd_help cmd_long cmd_subs cmd_func
-  mode=$shifu_mode_cmds
-  parent="$1"; shift; "$parent"; shifu_cmds="$cmd_subs"
-  while [ $# -ne 0 ]; do
-    arg="$1"; shift
-    arg_matched=''
-    for cmd in $shifu_cmds; do
-      _shifu_clear_cmd_vars
-      "$cmd"
-      [ "$arg" != "$cmd_name" ] && continue
-      arg_matched=true
-      [ -n "$cmd_func" ] && break
-      parent="$cmd"
-      shifu_cmds="$cmd_subs"
-      break
-    done
-    [ "$arg_matched" = true -a -n "$cmd_func" ] && break
-    [ "$arg_matched" = true -a -n "$cmd_subs" ] && continue
-    echo "unknown command: $arg"
-    shifu_help "$parent"
-    exit 1
-  done
-  [ "$1" = "-h" -o "$1" = "--help" ] && shifu_help "$cmd" || "$cmd_func" "$@"
-  shifu_var_restore mode parent arg arg_matched cmd cmd_name cmd_help cmd_long cmd_subs cmd_func
 }
 
 _shifu_clear_cmd_vars() {
@@ -177,51 +217,11 @@ _shifu_parse_arg() {
   fi
 }
 
-shifu_arg() {
-  case $mode in
-    $shifu_mode_help) _shifu_arg_help "$@" ;;
-    $shifu_mode_args) _shifu_parse_arg "$@" ;;
-    *) return
-  esac
-}
-
-shifu_save_remaining_args () {
+_shifu_save_remaining_args () {
 for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
 echo " "
 }
 
-shifu_parse_args() {
-  # 1: function, 2-: args to parse
-  shifu_var_store mode parse_stage case_stmt has_options
-  mode=$shifu_mode_args
-  parse_stage=0
-  case_stmt="case \$1 in -h|--help) shifu_help \$1; break ;; "
-  $1; shift # run the cmd function
-  [ $parse_stage -eq 0 ] && case_stmt="$case_stmt *) "
-  case_stmt="$case_stmt break ;; esac"
-  while true; do
-    eval "$case_stmt"
-  done
-  shifu_remaining_args=$(shifu_save_remaining_args "$@")
-  shifu_var_restore mode parse_stage case_stmt has_options
-}
-
 _shifu_add_to_help_string() {
   [ -z "$help_string" ] && help_string="$1" || help_string="$help_string\n\n$1"
-}
-
-shifu_help() {
-  shifu_var_store mode help_stage help_usage help_arguments help_options help_string has_options
-  mode=$shifu_mode_help
-  _shifu_clear_cmd_vars
-  help_stage=0 help_usage='' help_arguments='' help_options='' help_string=''
-  "$1"
-  [ -n "$help_usage" ] && help_usage="$cmd_name [OPTIONS] $help_usage"
-  [ -n "$cmd_help" ] && _shifu_add_to_help_string "$cmd_help"
-  [ -n "$cmd_long" ] && _shifu_add_to_help_string "$cmd_long"
-  [ -n "$help_usage" ] && _shifu_add_to_help_string "Usage\n\t$help_usage"
-  [ -n "$help_arguments" ] && _shifu_add_to_help_string "Arguments\n$help_arguments"
-  [ -n "$help_options" ] && _shifu_add_to_help_string "Options\n$help_options"
-  [ -n "$help_string" ] && echo "$help_string"
-  shifu_var_restore mode help_stage help_usage help_arguments help_options help_string has_options
 }
