Change no default option to required (#8)
* Start converting default option to required

* Make required local and global vars work together

* Add tests for global defaults, fix things

* Update help to say required options are required

* Update docs and assets

* Small readme adjustments

* Update sgh to not use no default

* Consistency

* Clarity

diff --git a/shifu b/shifu
--- a/shifu
+++ b/shifu
@@ -37,7 +37,7 @@ shifu_cmd_arg() {
     $shifu_mode_help_run)
       _shifu_arg_help "$@" ;;
     $shifu_mode_args_run)
-      [ -z "${shifu_cmd_subs:-}" ] && _shifu_update_case_stmt "$@" || _shifu_handle_arg_global "$@" ;;
+      [ -n "${shifu_cmd_func:-}" ] && _shifu_update_case_stmt "$@" || _shifu_handle_arg_global "$@" ;;
     $shifu_mode_args_comp)
       _shifu_update_comp_case_stmt "$@" ;;
   esac
@@ -91,10 +91,16 @@ shifu_less() {
 }
 
 shifu_run() {
-  case "$2" in
-    --tab-completion) _shifu_generate_tab_completion "$@" ;;
-    --shifu-complete) _shifu_complete "$@" ;;
-    *) _shifu_run "$@" ;;
+  # TODO: add tests for 0 & 1 cases
+  case $# in
+    0) echo "shifu_run requires at least one argument, got 0"
+       exit 1 ;;
+    1) _shifu_run "$@" ;;
+    *) case "$2" in
+        --tab-completion) _shifu_generate_tab_completion "$@" ;;
+        --shifu-complete) _shifu_complete "$@" ;;
+        *) _shifu_run "$@" ;;
+       esac ;;
   esac
 }
 
@@ -102,6 +108,7 @@ _shifu_run() {
   [ "${SHIFU_SET_X:-0}" = 1 ] && set -x
   shifu_mode=$shifu_mode_cmds_run
   shifu_parent="$1"; shifu_cmd="$1"; shift
+  shifu_required_variables=""
   "$shifu_parent"
   _shifu_set_for_looping shifu_cmds shifu_cmd_subs
   while [ $# -ne 0 -a -n "${shifu_cmd_subs:-}" ]; do
@@ -125,7 +132,7 @@ _shifu_run() {
     _shifu_help "$shifu_parent" 1
   done
   [ -z "$shifu_cmd_func" ] && { echo "$shifu_cmd_name requires arguments"; _shifu_help "$shifu_cmd" 1; }
-  [ "$1" = "-h" -o "$1" = "--help" ] && _shifu_help "$shifu_cmd" 0
+  case "${1:-}" in -h|--help) _shifu_help "$shifu_cmd" 0; esac
   _shifu_parse_args false "$shifu_cmd" "$@"
   [ $? -ne 0 ] && _shifu_help "$shifu_cmd" 1
   shift $_shifu_args_parsed
@@ -137,6 +144,7 @@ _shifu_parse_args() {
   shifu_mode=$shifu_mode_args_run
   shifu_parse_stage=0
   shifu_parse_local="$1"; shifu_cmd="$2"; shift 2
+  [ "$shifu_parse_local" = true ] && shifu_required_variables_local=""
   shifu_case_stmt="case \"\$1\" in"
   if [ "$shifu_parse_local" = false -a -n "${shifu_global_case:-}" ]; then
     _shifu_append_on_new_line shifu_case_stmt "  ${shifu_global_case:-}"
@@ -147,8 +155,19 @@ _shifu_parse_args() {
   _shifu_append_on_new_line shifu_case_stmt "    break;;"
   _shifu_append_on_new_line shifu_case_stmt "esac"
   _shifu_args_parsed=0
-  while true; do
+  while [ $# -ne 0 ]; do
     eval "$shifu_case_stmt"
+  done
+  if [ "$shifu_parse_local" = true ]; then
+    _shifu_set_for_looping shifu_required_vars shifu_required_variables_local
+  else
+    _shifu_set_for_looping shifu_required_vars shifu_required_variables
+  fi
+  for shifu_required_var in $shifu_required_vars; do
+    eval "if [ \"\${$shifu_required_var+set}\" != set ]; then
+      echo \"Required variable, $shifu_required_var, is not set\"
+      exit 1
+    fi"
   done
   [ "$shifu_parse_local" = true -o $# -eq 0 -o "$shifu_allow_options_anywhere" != false ] && return
   _shifu_error_if_options "$@"
@@ -182,17 +201,21 @@ _shifu_update_case_stmt() {
     _shifu_set_variable "$1" ""
     _shifu_update_case_stmt_positional_check "$1"
     _shifu_append_on_new_line shifu_case_stmt "    $1=\\\$1; shift; _shifu_ack_arg"
-  # option + argument without default
+  # option + argument, required
   elif [ $# -eq 2 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
-    _shifu_set_variable "$1" ""
+    if [ "$shifu_parse_local" = true ]; then
+      shifu_required_variables_local="${shifu_required_variables_local} $1"
+    else
+      shifu_required_variables="${shifu_required_variables} $1"
+    fi
     shifu_case_stmt="$shifu_case_stmt) $1=\$2; shift 2; _shifu_ack_arg 2 ;;"
-  # option + argument with default
+  # option + argument, with default
   elif [ $# -eq 3 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
     _shifu_set_variable "$1" "$2"
     shifu_case_stmt="$shifu_case_stmt) $1=\$2; shift 2; _shifu_ack_arg 2 ;;"
-  # option no argument, default-set
+  # option no argument, binary: default/set
   elif [ $# -eq 4 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
     _shifu_set_variable "$1" "$2"
@@ -219,17 +242,17 @@ _shifu_handle_arg_global() {
   # positional
   elif [ "$shifu_no_options" = true ]; then
     _shifu_error "Positional arguments cannot be global: $1"
-  # option + argument without default
+  # option + argument, required
   elif [ $# -eq 2 ]; then
-    _shifu_set_variable "$1" ""
-    shifu_global_case="${shifu_global_case:-}) $1=\$2; shift 2; _shifu_ack_arg 2 ;;"
-    shifu_global_help="${shifu_global_help:-} $1\n    $2"
-  # option + argument with default
+    shifu_required_variables="${shifu_required_variables} $1"
+    shifu_global_case="${shifu_global_case:-}) $1=\\\$2; shift 2; _shifu_ack_arg 2 ;;"
+    shifu_global_help="${shifu_global_help:-} [$1]\n    $2\n    Required"
+  # option + argument, with default
   elif [ $# -eq 3 ]; then
     _shifu_set_variable "$1" "$2"
-    shifu_global_case="${shifu_global_case:-}) $1=\$2; shift 2; _shifu_ack_arg 2 ;;"
-    shifu_global_help="${shifu_global_help:-} $1\n    $3\n    Default: $2"
-  # option no argument, default-set
+    shifu_global_case="${shifu_global_case:-}) $1=\\\$2; shift 2; _shifu_ack_arg 2 ;;"
+    shifu_global_help="${shifu_global_help:-} [$1]\n    $3\n    Default: $2"
+  # option no argument, binary: default/set
   elif [ $# -eq 4 ]; then
     _shifu_set_variable "$1" "$2"
     shifu_global_case="${shifu_global_case:-}) $1=$3; shift; _shifu_ack_arg ;;"
@@ -307,15 +330,15 @@ _shifu_arg_help() {
     fi
     shifu_help_usage="${shifu_help_usage:-} [$1]"
     shifu_help_arguments="${shifu_help_arguments:-}\n  $1\n    $2"
-  # option + argument without default
+  # option + argument, required
   elif [ $# -eq 2 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_help_stage
-    shifu_help_options="$shifu_help_options [$1]\n    $2"
-  # option + argument with default
+    shifu_help_options="$shifu_help_options [$1]\n    $2\n    Required"
+  # option + argument, with default
   elif [ $# -eq 3 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_help_stage
     shifu_help_options="$shifu_help_options [$1]\n    $3\n    Default: $2"
-  # option no argument default set
+  # option no argument, binary: default/set
   elif [ $# -eq 4 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_help_stage
     shifu_help_options="$shifu_help_options\n    $4\n    Default: ${2:-empty}, set: $3"
@@ -454,7 +477,7 @@ _shifu_update_comp_case_stmt() {
     elif [ $shifu_parse_stage -gt 1 ]; then
       _shifu_error "No arguments after remaining are declared: $1"
     fi
-  # option + argument without default
+  # option + argument, required
   elif [ $# -eq 2 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
     shifu_case_stmt="$shifu_case_stmt) shift;"
@@ -462,10 +485,10 @@ _shifu_update_comp_case_stmt() {
   elif [ $# -eq 3 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
     shifu_case_stmt="$shifu_case_stmt) shift;"
-  # option no argument, default-set
+  # option no argument, binary default/set
   elif [ $# -eq 4 ]; then
     _shifu_error_if_invalid_arg_order "$1" $shifu_parse_stage
-    # this has no value that could be completed
+    # has no value that could be completed
     shifu_case_stmt="$shifu_case_stmt)"
   fi
 }
@@ -507,9 +530,6 @@ _shifu_update_case_stmt_positional_check() {
     _shifu_append_on_new_line positional_clause "      _shifu_help \"\$shifu_cmd\" 1
     }"
     _shifu_append_on_new_line shifu_case_stmt "    $positional_clause"
-
-    # shifu_case_stmt="$shifu_case_stmt
-    #  $positional_clause echo 'Missing positional argument $1'; _shifu_help \"\$shifu_cmd\" 1; };"
 }
 
 _shifu_set_for_looping() {
