Start drying up some of this wet code

diff --git a/shifu b/shifu
--- a/shifu
+++ b/shifu
@@ -60,14 +60,13 @@ shifu_run() {
     parse_local=true
     _shifu_parse_args "$parent" "$@"
     mode=$shifu_mode_cmds
-    eval "$_shifu_align_args"
-    arg="$1"; shift
+    shift $_shifu_args_parsed
     arg_matched=''
     for cmd in $shifu_cmds; do
       _shifu_clear_cmd_vars
       "$cmd"
-      [ "$arg" != "$cmd_name" ] && continue
-      arg_matched=true
+      [ "$1" != "$cmd_name" ] && continue
+      arg_matched=true; shift
       [ -n "$cmd_func" ] && break
       parent="$cmd"
       shifu_cmds="$cmd_subs"
@@ -75,20 +74,18 @@ shifu_run() {
     done
     [ "$arg_matched" = true -a -n "$cmd_func" ] && break
     [ "$arg_matched" = true -a -n "$cmd_subs" ] && continue
-    [ "$arg" != "-h" -a "$arg" != "--help" ] && echo "Unknown command: $arg"
+    [ "$1" != "-h" -a "$1" != "--help" ] && echo "Unknown command: $1"
     shifu_help "$parent"
     exit 1
   done
   [ -z "$cmd_func" ] && { echo "$cmd_name" requires arguments; shifu_help "$cmd"; exit 1; }
   [ "$1" = "-h" -o "$1" = "--help" ] && { shifu_help "$cmd"; exit 0; }
   _shifu_parse_args "$cmd" "$@"
-  eval "$_shifu_align_args"
+  shift $_shifu_args_parsed
   "$cmd_func" "$@"
   shifu_var_restore mode parent parse_local parse_stage arg arg_matched global_help \
                     shifu_cmds cmd cmd_name cmd_help cmd_long cmd_subs cmd_func
 }
-
-_shifu_align_args="for shifu_counter in \$_shifu_args_parsed; do shift; done"
 
 shifu_help() {
   shifu_var_store mode help_stage help_usage help_arguments help_options help_string has_options subcmd_help
@@ -99,8 +96,8 @@ shifu_help() {
 
 shifu_var_store() {
   while [ $# -ne 0 ]; do
-    [ -z "$1" ] && { shift; continue; }
-    eval "[ -z \$shifu_${1}_shifu ] && shifu_${1}_shifu=\$$1 || \\
+    eval "[ -z "\$$1" ] && { shift; continue; }
+          [ -z \$shifu_${1}_shifu ] && shifu_${1}_shifu=\$$1 ||
           { echo \"Cannot use variable 'shifu_${1}_shifu'\"; exit 1; }"
     shift
   done
@@ -121,61 +118,53 @@ _shifu_parse_args() {
   case_stmt="case \"\$1\" in $global_case -h|--help) _shifu_help \"$cmd\"; exit 0 ;; "
   "$cmd"
   if [ $parse_stage -eq 0 -a parse_local != true ]; then
-    case_stmt="$case_stmt -*|--*) echo \"Invalid option: \$1\"; _shifu_help \"$cmd\"; exit 1 ;; "
-    case_stmt="$case_stmt *) "
+    _shifu_update_case_stmt_invalid_option
   fi
   case_stmt="$case_stmt break ;; esac"
-  _shifu_args_parsed=''
+  _shifu_args_parsed=0
   while true; do
     eval "$case_stmt"
   done
-  _shifu_args_parsed="${_shifu_args_parsed# }"
   shifu_var_restore parse_stage case_stmt has_options
 }
 
 _shifu_parse_arg() {
   has_options=0
-  [ $# -gt 1 -a "$1" != -- ] && { has_options=1; case_stmt="$case_stmt $1"; shift; }
+  [ "$1" != -- ] && { has_options=1; case_stmt="$case_stmt $1"; shift; }
   while [ $# -gt 1 -a "$1" != -- ]; do
     case_stmt="${case_stmt}|$1"; shift
   done; shift
   # remaining
   if [ $# -eq 1 -a parse_local != true ]; then
     if [ $parse_stage -eq 0 ]; then
-      case_stmt="$case_stmt -*|--*) echo \"Invalid option: \$1\"; _shifu_help \"\$cmd\"; exit 1 ;; "
-      case_stmt="$case_stmt *)"
+      _shifu_update_case_stmt_invalid_option
     fi
     parse_stage=2
   # positional
   elif [ $has_options -eq 0 -a parse_local != true ]; then
     if [ $parse_stage -eq 0 ]; then
       parse_stage=1
-      case_stmt="$case_stmt -*|--*) echo \"Invalid option: \$1\"; _shifu_help \"\$cmd\"; exit 1 ;; "
-      case_stmt="$case_stmt *)"
+      _shifu_update_case_stmt_invalid_option
     elif [ $parse_stage -gt 1 ]; then
       echo "No arguments after remaining are declared: $1"; exit 1;
     fi
-    eval "$1=" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
+    _shifu_set_variable "$1" ""
     case_stmt="$case_stmt [ \$# -eq 0 ] && { echo 'Missing positional argument $1'; exit 1; }; "
     case_stmt="$case_stmt $1=\$1; shift; _shifu_ack_arg; "
   # option + argument without default
   elif [ $# -eq 2 ]; then
-    [ $parse_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
-    eval "$1=" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
-    case_stmt="$case_stmt) $1=\$2; shift; shift; _shifu_ack_arg; _shifu_ack_arg ;; "
+    _shifu_error_if_invalid_arg_order "$1" $parse_stage
+    _shifu_set_variable "$1" ""
+    case_stmt="$case_stmt) $1=\$2; shift 2; _shifu_ack_arg 2 ;; "
   # option + argument with default
   elif [ $# -eq 3 ]; then
-    [ $parse_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
-    eval "$1=\"$2\"" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
-    case_stmt="$case_stmt) $1=\$2; shift; shift; _shifu_ack_arg; _shifu_ack_arg ;; "
+    _shifu_error_if_invalid_arg_order "$1" $parse_stage
+    _shifu_set_variable "$1" "$2"
+    case_stmt="$case_stmt) $1=\$2; shift 2; _shifu_ack_arg 2 ;; "
   # option no argument, default-set
   elif [ $# -eq 4 ]; then
-    [ $parse_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
-    eval "$1=\"$2\"" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
+    _shifu_error_if_invalid_arg_order "$1" $parse_stage
+    _shifu_set_variable "$1" "$2"
     case_stmt="$case_stmt) $1=$3; shift; _shifu_ack_arg ;; "
   fi
 }
@@ -201,30 +190,24 @@ _shifu_handle_arg_global() {
     echo "Positional arguments cannot be global"; exit 1
   # option + argument without default
   elif [ $# -eq 2 ]; then
-    [ $parse_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
-    eval "$1=" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
-    global_case="$global_case) $1=\$2; shift; shift; _shifu_ack_arg; _shifu_ack_arg ;; "
+    _shifu_set_variable "$1" ""
+    global_case="$global_case) $1=\$2; shift 2; _shifu_ack_arg 2 ;; "
     global_help="$global_help $1\n    $2"
   # option + argument with default
   elif [ $# -eq 3 ]; then
-    [ $parse_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
-    eval "$1=$2" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
-    global_case="$global_case) $1=\$2; shift; shift; _shifu_ack_arg; _shifu_ack_arg ;; "
+    _shifu_set_variable "$1" "$2"
+    global_case="$global_case) $1=\$2; shift 2; _shifu_ack_arg 2 ;; "
     global_help="$global_help $1\n    $3\n    Default: $2"
   # option no argument, default-set
   elif [ $# -eq 4 ]; then
-    [ $parse_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
-    eval "$1=$2" > /dev/null 2>&1
-    [ $? -ne 0 ] && { echo "Invalid variable name: $1"; exit 1; }
+    _shifu_set_variable "$1" "$2"
     global_case="$global_case) $1=$3; shift; _shifu_ack_arg ;; "
     global_help="$global_help\n    $4\n    Default: $2, set: $3"
   fi
 }
 
 _shifu_ack_arg() {
-  _shifu_args_parsed="$_shifu_args_parsed 1"
+  _shifu_args_parsed=$((_shifu_args_parsed + ${1:-1}))
 }
 
 _shifu_clear_cmd_vars() {
@@ -233,7 +216,7 @@ _shifu_clear_cmd_vars() {
 
 _shifu_arg_help() {
   has_options=0
-  [ $# -gt 1 -a "$1" != -- ] && { has_options=1; help_options="$help_options\n  $1"; shift; }
+  [ "$1" != -- ] && { has_options=1; help_options="$help_options\n  $1"; shift; }
   while [ $# -gt 1 -a "$1" != -- ]; do
     help_options="$help_options, $1"; shift
   done; shift
@@ -253,17 +236,36 @@ _shifu_arg_help() {
     help_arguments="$help_arguments\n  $1\n    $2"
   # option + argument without default
   elif [ $# -eq 2 ]; then
-    [ $help_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
+    _shifu_error_if_invalid_arg_order "$1" $help_stage
     help_options="$help_options [$1]\n    $2"
   # option + argument with default
   elif [ $# -eq 3 ]; then
-    [ $help_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
+    _shifu_error_if_invalid_arg_order "$1" $help_stage
     help_options="$help_options [$1]\n    $3\n    Default: $2"
   # option no argument default set
   elif [ $# -eq 4 ]; then
-    [ $help_stage -gt 0 ] && { echo "No options after positional/remaining arguments: $1"; exit 1; }
+    _shifu_error_if_invalid_arg_order "$1" $help_stage
     help_options="$help_options\n    $4\n    Default: $2, set: $3"
   fi
+}
+
+_shifu_update_case_stmt_invalid_option() {
+  case_stmt="$case_stmt
+    -*|--*) echo \"Invalid option: \$1\"; _shifu_help \"\$cmd\"; exit 1 ;;
+    *)"
+}
+
+_shifu_set_variable() {
+  eval "$1=\"$2\"" > /dev/null 2>&1
+  [ $? -eq 0 ] && return 0
+  echo "Invalid variable name: $1"
+  exit 1
+}
+
+_shifu_error_if_invalid_arg_order() {
+  [ $2 -eq 0 ] && return
+  echo "No options after positional/remaining arguments: $1"
+  exit 1
 }
 
 _shifu_help() {
